/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oyun_seviyeleri;

import Help.Help;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;

/**
 *
 * @author İLKER
 */
public class Custom extends javax.swing.JFrame {
int süre =0;
    /**
     * Creates new form Custom
     */
    public Custom() {
        initComponents();
        
         //geçen zamanın hesaplanması ve ekrana yazdırılması...
        Timer zaman = new Timer();
        TimerTask koronometre = new TimerTask() {
            @Override
            public void run() {

                String gecen_süre = " " + süre;
                jTextFieldTime.setText(gecen_süre);
                süre++;
            }
        };
        zaman.schedule(koronometre, 0, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonYeniden = new javax.swing.JButton();
        jTextFieldTime = new javax.swing.JTextField();
        jTextFieldMayınSayısı = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBeginner = new javax.swing.JMenuItem();
        jMenuItemIntermediate = new javax.swing.JMenuItem();
        jMenuItemExport = new javax.swing.JMenuItem();
        jMenuItemCustom = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMarks = new javax.swing.JMenuItem();
        jMenuItemColor = new javax.swing.JMenuItem();
        jMenuItemSound = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CUSTOM");

        jLabelMinimize.setBackground(new java.awt.Color(255, 153, 0));
        jLabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        jLabelExit.setBackground(new java.awt.Color(255, 153, 0));
        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(0, 0, 0));
        jLabelExit.setText("X");
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        jLabelExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabelExitKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(241, 169, 160));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jButtonYeniden.setBackground(new java.awt.Color(102, 255, 102));
        jButtonYeniden.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonYeniden.setForeground(new java.awt.Color(0, 0, 0));
        jButtonYeniden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYenidenActionPerformed(evt);
            }
        });

        jTextFieldTime.setEditable(false);
        jTextFieldTime.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldTime.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldTime.setForeground(new java.awt.Color(242, 38, 19));
        jTextFieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimeActionPerformed(evt);
            }
        });

        jTextFieldMayınSayısı.setEditable(false);
        jTextFieldMayınSayısı.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldMayınSayısı.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldMayınSayısı.setForeground(new java.awt.Color(242, 38, 19));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" BU LEVEL İÇİN OYUNUN BU SÜRÜMÜNDE HİZMET VERİLMEMEKTEDİR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldMayınSayısı, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButtonYeniden, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonYeniden, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMayınSayısı, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize)
                .addGap(18, 18, 18)
                .addComponent(jLabelExit)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinimize)
                    .addComponent(jLabelExit)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 102));
        jMenuBar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jMenuBar1KeyTyped(evt);
            }
        });

        jMenu1.setBackground(new java.awt.Color(0, 204, 204));
        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("OYUN");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setDoubleBuffered(true);

        jMenuItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemNew.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemNew.setText("New");
        jMenuItemNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemNewMouseClicked(evt);
            }
        });
        jMenuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNew);
        jMenu1.add(jSeparator1);

        jMenuItemBeginner.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemBeginner.setBackground(new java.awt.Color(0, 255, 204));
        jMenuItemBeginner.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemBeginner.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItemBeginner.setText("Beginner");
        jMenuItemBeginner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemBeginner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemBeginnerMouseClicked(evt);
            }
        });
        jMenuItemBeginner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBeginnerActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemBeginner);

        jMenuItemIntermediate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemIntermediate.setBackground(new java.awt.Color(0, 255, 204));
        jMenuItemIntermediate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemIntermediate.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItemIntermediate.setText("Intermediate");
        jMenuItemIntermediate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemIntermediate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemIntermediateMouseClicked(evt);
            }
        });
        jMenuItemIntermediate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIntermediateActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemIntermediate);

        jMenuItemExport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemExport.setBackground(new java.awt.Color(0, 255, 204));
        jMenuItemExport.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemExport.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItemExport.setText("Export");
        jMenuItemExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExportActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExport);

        jMenuItemCustom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemCustom.setBackground(new java.awt.Color(0, 255, 204));
        jMenuItemCustom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemCustom.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItemCustom.setText("Custom");
        jMenuItemCustom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCustom);
        jMenu1.add(jSeparator2);

        jMenuItemMarks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemMarks.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemMarks.setText("Marks (?)");
        jMenuItemMarks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(jMenuItemMarks);

        jMenuItemColor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemColor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemColor.setText("Color");
        jMenuItemColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemColorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemColor);

        jMenuItemSound.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemSound.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemSound.setText("Sound");
        jMenuItemSound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(jMenuItemSound);
        jMenu1.add(jSeparator3);
        jMenu1.add(jSeparator4);

        jMenuItemHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemHelp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemHelp.setText("HELP");
        jMenuItemHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemHelp);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 204, 204));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemNewMouseClicked

        Default dft = new Default();
        dft.setVisible(true);
        dft.pack();
        dft.setLocationRelativeTo(null);
        dft.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItemNewMouseClicked

    private void jMenuItemBeginnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemBeginnerMouseClicked

        Beginner bgn = new Beginner();
        bgn.setVisible(true);
        bgn.pack();
        bgn.setLocationRelativeTo(null);
        bgn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItemBeginnerMouseClicked

    private void jMenuItemIntermediateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemIntermediateMouseClicked
        Intermediate ınt = new Intermediate();
        ınt.setVisible(true);
        ınt.pack();
        ınt.setLocationRelativeTo(null);
        ınt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItemIntermediateMouseClicked

    private void jMenuBar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuBar1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1KeyTyped

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked

        this.setState(JFrame.ICONIFIED);//pnecerenin küçültülmesini sağlar.
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked

        System.exit(0);//fare ile tıklayınca pencereyi kapatmayı sağlar
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelExitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelExitKeyTyped

    private void jMenuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewActionPerformed

        Default dft = new Default();
        dft.setVisible(true);
        dft.pack();
        dft.setLocationRelativeTo(null);
        dft.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jMenuItemNewActionPerformed

    private void jMenuItemBeginnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBeginnerActionPerformed

        Beginner bgn = new Beginner();
        bgn.setVisible(true);
        bgn.pack();
        bgn.setLocationRelativeTo(null);
        bgn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jMenuItemBeginnerActionPerformed

    private void jMenuItemIntermediateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIntermediateActionPerformed

        Intermediate ınt = new Intermediate();
        ınt.setVisible(true);
        ınt.pack();
        ınt.setLocationRelativeTo(null);
        ınt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();


    }//GEN-LAST:event_jMenuItemIntermediateActionPerformed

    private void jMenuItemExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExportActionPerformed

        Export exp = new Export();
        exp.setVisible(true);
        exp.pack();
        exp.setLocationRelativeTo(null);
        exp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jMenuItemExportActionPerformed

    private void jMenuItemCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomActionPerformed

        CustomField csf = new CustomField();
        csf.setVisible(true);
        csf.pack();
        csf.setLocationRelativeTo(null);
        csf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();


    }//GEN-LAST:event_jMenuItemCustomActionPerformed

    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed

        Help help = new Help();
        help.setVisible(true);
        help.pack();
        help.setLocationRelativeTo(null);
        help.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jButtonYenidenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYenidenActionPerformed

        CustomField csf = new CustomField();
        csf.setVisible(true);
        csf.pack();
        csf.setLocationRelativeTo(null);
        csf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonYenidenActionPerformed

    private void jTextFieldTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeActionPerformed

    private void jMenuItemColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemColorActionPerformed
        Color color = new Color();
        color.setVisible(true);
        color.pack();
        color.setLocationRelativeTo(null);
        color.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItemColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Custom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Custom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Custom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Custom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Custom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonYeniden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBeginner;
    private javax.swing.JMenuItem jMenuItemColor;
    private javax.swing.JMenuItem jMenuItemCustom;
    private javax.swing.JMenuItem jMenuItemExport;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemIntermediate;
    private javax.swing.JMenuItem jMenuItemMarks;
    private javax.swing.JMenuItem jMenuItemNew;
    private javax.swing.JMenuItem jMenuItemSound;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTextField jTextFieldMayınSayısı;
    private javax.swing.JTextField jTextFieldTime;
    // End of variables declaration//GEN-END:variables
}
