/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Help;

import oyun_seviyeleri.*;
import javax.swing.JFrame;

/**
 *
 * @author İLKER
 */
public class Help_genel_bilgi extends javax.swing.JFrame {

    public Help_genel_bilgi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaGenelBilgi = new javax.swing.JTextArea();
        jButtonAnaMenü = new javax.swing.JButton();
        jButtonSonraki = new javax.swing.JButton();
        jLabelGenelBilgiBaslık = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 8, 14));

        jPanel2.setBackground(new java.awt.Color(221, 221, 123));
        jPanel2.setForeground(new java.awt.Color(18, 1, 1));

        jTextAreaGenelBilgi.setEditable(false);
        jTextAreaGenelBilgi.setBackground(new java.awt.Color(221, 221, 123));
        jTextAreaGenelBilgi.setColumns(20);
        jTextAreaGenelBilgi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextAreaGenelBilgi.setForeground(new java.awt.Color(189, 65, 137));
        jTextAreaGenelBilgi.setRows(5);
        jTextAreaGenelBilgi.setText(" Sol üst köşede “GAME” yani “OYUN” menüsü\n bulunmaktadır. \n GAME menüsü içinde 10 tane buton bulunmaktadır. \nAyrıca Mayın Tarlası oyununun 3 farklı zorluk derecesi\n bulunmaktadır. ");
        jTextAreaGenelBilgi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextAreaGenelBilgi);

        jButtonAnaMenü.setBackground(new java.awt.Color(255, 153, 51));
        jButtonAnaMenü.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAnaMenü.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAnaMenü.setText("ana menü");
        jButtonAnaMenü.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnaMenü.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnaMenüActionPerformed(evt);
            }
        });

        jButtonSonraki.setBackground(new java.awt.Color(255, 153, 51));
        jButtonSonraki.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSonraki.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSonraki.setText("sonraki");
        jButtonSonraki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSonraki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSonrakiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAnaMenü)
                .addGap(18, 18, 18)
                .addComponent(jButtonSonraki)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnaMenü)
                    .addComponent(jButtonSonraki))
                .addGap(18, 18, 18))
        );

        jLabelGenelBilgiBaslık.setBackground(new java.awt.Color(167, 66, 6));
        jLabelGenelBilgiBaslık.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelGenelBilgiBaslık.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGenelBilgiBaslık.setText("Genel Bilgi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGenelBilgiBaslık)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabelGenelBilgiBaslık)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnaMenüActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaMenüActionPerformed
        Help ana_menü = new Help();
        ana_menü.setVisible(true);
        ana_menü.pack();
        ana_menü.setLocationRelativeTo(null);
        ana_menü.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonAnaMenüActionPerformed

    private void jButtonSonrakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSonrakiActionPerformed
        Help_oyun_menüsü menü = new Help_oyun_menüsü();
        menü.setVisible(true);
        menü.pack();
        menü.setLocationRelativeTo(null);
        menü.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonSonrakiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help_genel_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help_genel_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help_genel_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help_genel_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help_genel_bilgi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnaMenü;
    private javax.swing.JButton jButtonSonraki;
    private javax.swing.JLabel jLabelGenelBilgiBaslık;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaGenelBilgi;
    // End of variables declaration//GEN-END:variables
}
