/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Help;

import Help.*;
import javax.swing.JFrame;
import javax.swing.text.DefaultCaret;
import oyun_seviyeleri.*;

/**
 *
 * @author İLKER
 */
public  class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHelpBaslık = new javax.swing.JLabel();
        jButtonHelpiAnladım = new javax.swing.JButton();
        jButtonGenelBilgi = new javax.swing.JButton();
        jButtonSayılarınAnlamı = new javax.swing.JButton();
        jButtonTaktikler = new javax.swing.JButton();
        jButtonTarihce = new javax.swing.JButton();
        jButtonOyunMenüsü = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabelHelpBaslık.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelHelpBaslık.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHelpBaslık.setText("HELP :-:-:-:-: YARDIMM!!!!");

        jButtonHelpiAnladım.setBackground(new java.awt.Color(204, 204, 204));
        jButtonHelpiAnladım.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonHelpiAnladım.setForeground(new java.awt.Color(204, 0, 204));
        jButtonHelpiAnladım.setText("ANLADIM TEŞEKKÜRLER.........GERİ DÖNEBİLİRİZ🙂");
        jButtonHelpiAnladım.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHelpiAnladım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpiAnladımActionPerformed(evt);
            }
        });

        jButtonGenelBilgi.setBackground(new java.awt.Color(102, 102, 255));
        jButtonGenelBilgi.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jButtonGenelBilgi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenelBilgi.setText("GENEL BİLGİ....");
        jButtonGenelBilgi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGenelBilgi.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonGenelBilgi.setHideActionText(true);
        jButtonGenelBilgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenelBilgiActionPerformed(evt);
            }
        });

        jButtonSayılarınAnlamı.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSayılarınAnlamı.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jButtonSayılarınAnlamı.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSayılarınAnlamı.setText("SAYILARIN ANLAMI....");
        jButtonSayılarınAnlamı.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSayılarınAnlamı.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonSayılarınAnlamı.setHideActionText(true);
        jButtonSayılarınAnlamı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSayılarınAnlamıActionPerformed(evt);
            }
        });

        jButtonTaktikler.setBackground(new java.awt.Color(102, 102, 255));
        jButtonTaktikler.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jButtonTaktikler.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTaktikler.setText("OYUNUN TAKTİKLERİ....");
        jButtonTaktikler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTaktikler.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonTaktikler.setHideActionText(true);
        jButtonTaktikler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaktiklerActionPerformed(evt);
            }
        });

        jButtonTarihce.setBackground(new java.awt.Color(102, 102, 255));
        jButtonTarihce.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jButtonTarihce.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTarihce.setText("OYUNUN TARİHÇESİ....");
        jButtonTarihce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTarihce.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonTarihce.setHideActionText(true);
        jButtonTarihce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTarihceActionPerformed(evt);
            }
        });

        jButtonOyunMenüsü.setBackground(new java.awt.Color(102, 102, 255));
        jButtonOyunMenüsü.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jButtonOyunMenüsü.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOyunMenüsü.setText("OYUN MENÜSÜ....");
        jButtonOyunMenüsü.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOyunMenüsü.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonOyunMenüsü.setHideActionText(true);
        jButtonOyunMenüsü.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOyunMenüsüActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonOyunMenüsü)
                        .addComponent(jButtonGenelBilgi)
                        .addComponent(jButtonSayılarınAnlamı)
                        .addComponent(jButtonTaktikler)
                        .addComponent(jButtonTarihce))
                    .addComponent(jLabelHelpBaslık))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jButtonHelpiAnladım)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHelpBaslık)
                .addGap(18, 18, 18)
                .addComponent(jButtonGenelBilgi)
                .addGap(18, 18, 18)
                .addComponent(jButtonOyunMenüsü)
                .addGap(18, 18, 18)
                .addComponent(jButtonSayılarınAnlamı)
                .addGap(18, 18, 18)
                .addComponent(jButtonTaktikler)
                .addGap(18, 18, 18)
                .addComponent(jButtonTarihce)
                .addGap(48, 48, 48)
                .addComponent(jButtonHelpiAnladım)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHelpiAnladımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpiAnladımActionPerformed
        // TODO add your handling code here:
        Giris giris=new Giris();
        giris.setVisible(true);
        giris.pack();
        giris.setLocationRelativeTo(null);
        giris.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonHelpiAnladımActionPerformed

    private void jButtonSayılarınAnlamıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSayılarınAnlamıActionPerformed

        Help_sayıların_anlamı sayılarınAnlamı=new Help_sayıların_anlamı();
        sayılarınAnlamı.setVisible(true);
        sayılarınAnlamı.pack();
        sayılarınAnlamı.setLocationRelativeTo(null);
        sayılarınAnlamı.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jButtonSayılarınAnlamıActionPerformed

    private void jButtonOyunMenüsüActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOyunMenüsüActionPerformed
        Help_oyun_menüsü oyunMenüsü=new Help_oyun_menüsü();
        oyunMenüsü.setVisible(true);
        oyunMenüsü.pack();
        oyunMenüsü.setLocationRelativeTo(null);
        oyunMenüsü.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jButtonOyunMenüsüActionPerformed

    private void jButtonGenelBilgiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenelBilgiActionPerformed

        Help_genel_bilgi genelBilgi=new Help_genel_bilgi();
        genelBilgi.setVisible(true);
        genelBilgi.pack();
        genelBilgi.setLocationRelativeTo(null);
        genelBilgi.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jButtonGenelBilgiActionPerformed

    private void jButtonTaktiklerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaktiklerActionPerformed

        Help_Taktikler taktik=new Help_Taktikler();
        taktik.setVisible(true);
        taktik.pack();
        taktik.setLocationRelativeTo(null);
        taktik.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jButtonTaktiklerActionPerformed

    private void jButtonTarihceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTarihceActionPerformed

        Help_oyunun_tarihçesi tarihce=new Help_oyunun_tarihçesi();
        tarihce.setVisible(true);
        tarihce.pack();
        tarihce.setLocationRelativeTo(null);
        tarihce.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jButtonTarihceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenelBilgi;
    private javax.swing.JButton jButtonHelpiAnladım;
    private javax.swing.JButton jButtonOyunMenüsü;
    private javax.swing.JButton jButtonSayılarınAnlamı;
    private javax.swing.JButton jButtonTaktikler;
    private javax.swing.JButton jButtonTarihce;
    private javax.swing.JLabel jLabelHelpBaslık;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
