/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Help;

import javax.swing.JFrame;
import oyun_seviyeleri.*;

/**
 *
 * @author İLKER
 */
public class Help_Taktikler extends javax.swing.JFrame {

    /**
     * Creates new form Help_oyunun_anlam_ve_önemi
     */
    public Help_Taktikler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaTaktikler = new javax.swing.JTextArea();
        jButtonSonraki = new javax.swing.JButton();
        jButtonAnaMenü = new javax.swing.JButton();
        jLabelTaktiklerBaslık = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel11.setBackground(new java.awt.Color(153, 255, 153));
        jPanel11.setForeground(new java.awt.Color(255, 8, 14));

        jPanel12.setBackground(new java.awt.Color(221, 221, 123));
        jPanel12.setForeground(new java.awt.Color(18, 1, 1));

        jTextAreaTaktikler.setEditable(false);
        jTextAreaTaktikler.setBackground(new java.awt.Color(221, 221, 123));
        jTextAreaTaktikler.setColumns(20);
        jTextAreaTaktikler.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextAreaTaktikler.setForeground(new java.awt.Color(189, 65, 137));
        jTextAreaTaktikler.setRows(5);
        jTextAreaTaktikler.setText("Burada yazan tüm taktikler döndürülebilmektedir.\n\n1-2-2-1 taktiği : \nBir düzlemde sayılar 1-2-2-1 şeklinde sıralanmış ise 2’lerin altı mayın 1’lerin altı boştur.\n\n1-2-1 taktiği : \nBir düzlemde sayılar 1-2-1 şeklinde sıralanmış ise 1’lerin altı dolu 2’nin altı boştur.\n\n1-2-3-2-1 taktiği : \nBir düzlemde sayılar 1-2-3-2-1 şeklinde sıralanmışsa 2 ve 3 sayılarının altı dolu 1 sayılarının\naltı boştur. 3’ten sonsuz tane yerleştirilebilir.(1-2-3-3-…..-3-3-2-1)\n\n1-2 taktiği: \nBir alanda eğer 2'nin 1'e uzak olan kısmında sadece bir yer açılmamışsa o açılmamış olan yer mayındır;\n1'in 2'ye uzak olan kısmı boştur.\n\n1-3 taktiği: \nBir alanda eğer 3'ün 1'e uzak olan kısmında sadece iki yer açılmamışsa o açılmamış olan yerler mayındır;\n1'in 3'e uzak olan kısmı boştur.\n\n1-4 taktiği: \nBir alanda eğer 4'ün 1'e uzak olan kısmında yerler açılmamışsa o yerler mayındır;\n1'in 4'ye uzak olan kısmı boştur.\n\n4-1-4 taktiği: \nEğer ki sayılar 4-1-4 şeklinde sıralanmış ise 4'lerin 1'e uzak kenarlarının tamamı mayındır ve 4'lerin ortak \nköşelerinden biri mayındır. 1'in diğer yanları boştur.\n\n41-3?-41 taktiği: \nEğer ki sayılar üste 1-bilinmeyen kare-1 ;altta 4-3-4 şeklinde sekil almış ise 4'lerin 1'ye uzak kısımlarının tamamı mayındır. ,\n1'lerin arasında kalan kare de boştur ve 1'lerin 4'e uzak olan kısımlarının tamamı boştur, 1 ve 4'ün arasındaki kareler belirsizdir.\n\n42-30-42 taktiği: \nEğer sayılar üstte 1-0-1 alt ise 4-3-4 şeklinde sıralanmış şekilde 2'nin 4'e uzak olan kısımları boş ise , \n4'lerin 3'e ve 2'lere uzak olan çaprazları boştur, geri kalan tüm alanlarda mayın vardır;eğer ki dolu ise 2 ve 4'ün arasındaki\nkareler belirsiz olup 4'lerin 2'ye uzak kısımlarının tamamı mayındır.\n\n1-31 taktiği: \nEğer sayılardan 1'ler birbirine çapraz olup da 3 ortak kenarlarından birindeyse diğer ortak kenar ve 1'lerin 3'e uzak kısımları \nboş olup 3'ün 1'lere uzak olan karesi doludur, 1-3 arasında kalan kareler belirsizdir.");
        jTextAreaTaktikler.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane6.setViewportView(jTextAreaTaktikler);

        jButtonSonraki.setBackground(new java.awt.Color(255, 153, 51));
        jButtonSonraki.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSonraki.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSonraki.setText("sonraki");
        jButtonSonraki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSonraki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSonrakiActionPerformed(evt);
            }
        });

        jButtonAnaMenü.setBackground(new java.awt.Color(255, 153, 51));
        jButtonAnaMenü.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAnaMenü.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAnaMenü.setText("ana menü");
        jButtonAnaMenü.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnaMenü.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnaMenüActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAnaMenü)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSonraki)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnaMenü)
                    .addComponent(jButtonSonraki)))
        );

        jLabelTaktiklerBaslık.setBackground(new java.awt.Color(167, 66, 6));
        jLabelTaktiklerBaslık.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelTaktiklerBaslık.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTaktiklerBaslık.setText("TAKTİKLER :)");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTaktiklerBaslık)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTaktiklerBaslık)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSonrakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSonrakiActionPerformed
        Help_oyunun_tarihçesi tatrihce=new Help_oyunun_tarihçesi();
        tatrihce.setVisible(true);
        tatrihce.pack();
        tatrihce.setLocationRelativeTo(null);
        tatrihce.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonSonrakiActionPerformed

    private void jButtonAnaMenüActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaMenüActionPerformed
        Help ana_menü=new Help();
        ana_menü.setVisible(true);
        ana_menü.pack();
        ana_menü.setLocationRelativeTo(null);
        ana_menü.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonAnaMenüActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help_Taktikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help_Taktikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help_Taktikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help_Taktikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help_Taktikler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnaMenü;
    private javax.swing.JButton jButtonSonraki;
    private javax.swing.JLabel jLabelTaktiklerBaslık;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextAreaTaktikler;
    // End of variables declaration//GEN-END:variables
}
