/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Help;

import javax.swing.JFrame;
import oyun_seviyeleri.*;

/**
 *
 * @author İLKER
 */
public class Help_oyun_menüsü extends javax.swing.JFrame {

    /**
     * Creates new form Help_oyun_menüsü
     */
    public Help_oyun_menüsü() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHelpOyunMenüsü = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelOyunMenüsüBaslık = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 8, 14));

        jPanel2.setBackground(new java.awt.Color(221, 221, 123));
        jPanel2.setForeground(new java.awt.Color(18, 1, 1));

        jTextAreaHelpOyunMenüsü.setEditable(false);
        jTextAreaHelpOyunMenüsü.setBackground(new java.awt.Color(221, 221, 123));
        jTextAreaHelpOyunMenüsü.setColumns(20);
        jTextAreaHelpOyunMenüsü.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextAreaHelpOyunMenüsü.setForeground(new java.awt.Color(189, 65, 137));
        jTextAreaHelpOyunMenüsü.setRows(5);
        jTextAreaHelpOyunMenüsü.setText("\n• “NEW” butonuna basarak yeni bir oyun açabilirsiniz. \n\n• “BEGINNER” zorluk derecesi olarak başlangıç yani temel seviyede yeni bir oyun açılır. \n\n• 9×9 kutudan oluşur ve oyun alanında 10 tane mayın gizlenmiştir. \n\n• “INTERMEDIATE” zorluk derecesi olarak orta düzey yani normal seviyede \nyeni bir oyun açar. 16×16 kutudan oluşur ve oyun alanında da 40 tane mayın gizlenmiştir. \n\n• “EXPERT” zorluk seviyesi olarak uzman yada ileri düzey yeni bir oyun açar. \n16×30 kutudan oluşur ve oyun alanında da 99 tane mayın gizlenmiştir. \n• “CUSTOM” seçeneği ile oyun alanı boyutunu ve gizlenen mayın sayısını siz belirliyorsunuz. \nCUSTOM butonuna basınca yukarıdaki şekildeki gibi bir pencere karşımıza çıkar. \nBu pencereden oyun alanının yüksekliğini, genişliğini ve gizlenmiş olan mayın sayısını manüel olarak\n elle girebiliyoruz. \n• “HEIGHT” oyun ekranı yüksekliğinin kaç kareden oluşacağını belirler. \n• “WIDTH” oyun ekranının genişliğinin kaç kareden oluşacağını belirler. \n• “MINES” ekranda gizlenecek mayın sayısını belirler. \n \nEkranın sol üst köşesinde bulunan ve içinde kırmızı renkte rakam yazan kısım gizlenmiş olan \nmayın sayısını gösterir. Her yeni mayın bulduğunuzda bu rakam 1 azalır. \nBu rakam “0” sıfır olunca oyunu bitiriyorsunuz. \n\nSağ üst köşede sürekli artan sayı ise oyunda geçirmiş olduğunuz zamanı saniye cinsinden gösterir. ");
        jTextAreaHelpOyunMenüsü.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextAreaHelpOyunMenüsü);

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("sonraki");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("ana menü");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(648, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabelOyunMenüsüBaslık.setBackground(new java.awt.Color(167, 66, 6));
        jLabelOyunMenüsüBaslık.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelOyunMenüsüBaslık.setForeground(new java.awt.Color(0, 0, 0));
        jLabelOyunMenüsüBaslık.setText("Oyun Menüsü");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOyunMenüsüBaslık)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOyunMenüsüBaslık)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Help_sayıların_anlamı sayılarınAnlamı = new Help_sayıların_anlamı();
        sayılarınAnlamı.setVisible(true);
        sayılarınAnlamı.pack();
        sayılarınAnlamı.setLocationRelativeTo(null);
        sayılarınAnlamı.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Help ana_menü = new Help();
        ana_menü.setVisible(true);
        ana_menü.pack();
        ana_menü.setLocationRelativeTo(null);
        ana_menü.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help_oyun_menüsü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help_oyun_menüsü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help_oyun_menüsü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help_oyun_menüsü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help_oyun_menüsü().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelOyunMenüsüBaslık;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaHelpOyunMenüsü;
    // End of variables declaration//GEN-END:variables
}
