/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Uyarılar;
import javax.swing.JFrame;
import oyun_seviyeleri.*;
/**
 *
 * @author İLKER
 */
public class Vazgeçme extends javax.swing.JFrame {

    /**
     * Creates new form Vazgeçme
     */
    public Vazgeçme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVazgecme = new javax.swing.JTextArea();
        jButtonBaslamakİstiyorum = new javax.swing.JButton();
        jButtonBelkiDahaSonra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(221, 214, 20));

        jTextAreaVazgecme.setEditable(false);
        jTextAreaVazgecme.setBackground(new java.awt.Color(221, 214, 20));
        jTextAreaVazgecme.setColumns(20);
        jTextAreaVazgecme.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextAreaVazgecme.setForeground(new java.awt.Color(189, 12, 14));
        jTextAreaVazgecme.setRows(5);
        jTextAreaVazgecme.setText("nasıl ki bir işe başlamakta zorlanıyorsak,\nböylesine heyecanlı bir oyuna da başlamakta\no kadar kararsız kalıp zorlanabiliriz...\n...DURMA....                    \n                   ...BAŞLA.....\n                                       ...VE KENDİNİ GÖSTER...");
        jTextAreaVazgecme.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextAreaVazgecme);

        jButtonBaslamakİstiyorum.setBackground(new java.awt.Color(230, 49, 211));
        jButtonBaslamakİstiyorum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonBaslamakİstiyorum.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBaslamakİstiyorum.setText("BAŞLAMAK İSTİYORUM");
        jButtonBaslamakİstiyorum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBaslamakİstiyorum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBaslamakİstiyorum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaslamakİstiyorumActionPerformed(evt);
            }
        });

        jButtonBelkiDahaSonra.setBackground(new java.awt.Color(221, 214, 20));
        jButtonBelkiDahaSonra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonBelkiDahaSonra.setForeground(new java.awt.Color(102, 102, 102));
        jButtonBelkiDahaSonra.setText("ŞİMDİLİK KALSIN...belkiDahaSonra");
        jButtonBelkiDahaSonra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBelkiDahaSonra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBelkiDahaSonraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBelkiDahaSonra)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBaslamakİstiyorum))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBaslamakİstiyorum)
                    .addComponent(jButtonBelkiDahaSonra))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBaslamakİstiyorumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaslamakİstiyorumActionPerformed

        Default dft = new Default();
        dft.setVisible(true);
        dft.pack();
        dft.setLocationRelativeTo(null);
        dft.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jButtonBaslamakİstiyorumActionPerformed

    private void jButtonBelkiDahaSonraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBelkiDahaSonraActionPerformed

        System.exit(WIDTH);
        
    }//GEN-LAST:event_jButtonBelkiDahaSonraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vazgeçme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vazgeçme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vazgeçme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vazgeçme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vazgeçme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBaslamakİstiyorum;
    private javax.swing.JButton jButtonBelkiDahaSonra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaVazgecme;
    // End of variables declaration//GEN-END:variables
}
